### ISSUE TITLE
-p no:terminal no longer works

### ISSUE THREAD

**Issue by smarlowucf** [pytest-dev/pytest-testinfra#451]
Attempting to disable terminal output from pytest yields an internal error:

`pytest -p no:terminal --collect-only`

```
NTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/smarlow/projects/venvs/ipa/lib64/python3.7/site-packages/_pytest/main.py", line 201, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/home/smarlow/projects/venvs/ipa/lib64/python3.7/site-packages/_pytest/config/__init__.py", line 668, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/home/smarlow/projects/venvs/ipa/lib64/python3.7/site-packages/pluggy/hooks.py", line 311, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/smarlow/projects/venvs/ipa/lib64/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/smarlow/projects/venvs/ipa/lib64/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/smarlow/projects/venvs/ipa/lib64/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/smarlow/projects/venvs/ipa/lib64/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/smarlow/projects/venvs/ipa/lib64/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/smarlow/projects/venvs/ipa/lib64/python3.7/site-packages/testinfra/plugin.py", line 187, in pytest_configure
INTERNALERROR>     if config.option.verbose > 1:
INTERNALERROR> AttributeError: 'Namespace' object has no attribute 'verbose'
```

**Comment by smarlowucf** [comment]
This started failing in pytest==4.4.0...

**Comment by smarlowucf** [comment]
Checking the attr seems to fix the issue https://github.com/philpep/testinfra/blob/master/testinfra/plugin.py#L187:

`if hasattr(config.option, 'verbose') and config.option.verbose > 1`

Not sure if this is the best solution but it seems like these options are not guaranteed to be set now.
